CKPT_PERIOD: 1
DEVICE: cuda:0
DISP_PERIOD: 10
EPS_P: 0.98
EVAL_PERIOD: 1
EVAL_USE_CACHE: false
EVAL_USE_CBGM: false
EVAL_USE_GT: false
HM_THRESH: 0.5
INPUT:
  BATCH_SIZE_TEST: 1
  BATCH_SIZE_TRAIN: 2
  DATASET: CUHK-SYSU
  DATA_ROOT: /home/guojian/paper_project/CUHK-SYSU
  MAX_SIZE: 1500
  MIN_SIZE: 900
  NUM_WORKERS_TEST: 1
  NUM_WORKERS_TRAIN: 5
  TDATASET: PRW
  TDATA_ROOT: /home/guojian/paper_project/PRW-v16.04.20
LOCAL_RANK: -1
MODEL:
  DA_HEADS:
    DA_CST_LOSS_WEIGHT: 0.1
    DA_IMG_LOSS_WEIGHT: 1.0
    DA_INS_LOSS_WEIGHT: 1.0
    LW_DA_INS: 0.02
  ROI_HEAD:
    BATCH_SIZE_TRAIN: 128
    BN_NECK: true
    DETECTIONS_PER_IMAGE_TEST: 300
    NEG_THRESH_TRAIN: 0.5
    NMS_THRESH_TEST: 0.4
    POS_FRAC_TRAIN: 0.5
    POS_THRESH_TRAIN: 0.5
    SCORE_THRESH_TEST: 0.5
  RPN:
    BATCH_SIZE_TRAIN: 256
    NEG_THRESH_TRAIN: 0.3
    NMS_THRESH: 0.7
    POST_NMS_TOPN_TEST: 300
    POST_NMS_TOPN_TRAIN: 2000
    POS_FRAC_TRAIN: 0.5
    POS_THRESH_TRAIN: 0.7
    PRE_NMS_TOPN_TEST: 6000
    PRE_NMS_TOPN_TRAIN: 12000
  SPD:
    SPD_IN_CHANNELS: 1024
    SPD_OUT_CHANNELS: 1024
    SPD_THRESH: 60
    USE_SPD: false
  UPDATE_FACTOR:
    OFFLINE: 0.2
    ONLINE: 0.2
OUTPUT_DIR: ./exp_cuhk_da
SEED: 1
SOLVER:
  BASE_LR: 0.0024
  CLIP_GRADIENTS: 10.0
  GAMMA: 0.1
  LR_DECAY_MILESTONES:
  - 16
  LW_BOX_CLS: 1
  LW_BOX_REG: 1
  LW_BOX_REID: 1
  LW_BOX_REID_T: 0.1
  LW_DA_INS: 0.98
  LW_PROPOSAL_CLS: 1
  LW_PROPOSAL_REG: 10
  LW_RPN_CLS: 1
  LW_RPN_REG: 1
  MAX_EPOCHS: 24
  SGD_MOMENTUM: 0.9
  WARMUP_FACTOR: 0.001
  WEIGHT_DECAY: 0.0005
TARGET_REID_START: 8
TF_BOARD: true
