OUTPUT_DIR: "./exp_cuhk_da_prw"
INPUT:
  TDATASET: "CUHK-SYSU"
  DATASET: "PRW"
  TDATA_ROOT: "/home/guojian/paper_project/CUHK-SYSU"
  DATA_ROOT: "/home/guojian/paper_project/PRW-v16.04.20"
  BATCH_SIZE_TRAIN: 2
SOLVER:
  MAX_EPOCHS: 25
  BASE_LR: 0.0024
  LW_BOX_REID_T: 0.5
MODEL:
  DA_HEADS:
    DA_IMG_LOSS_WEIGHT: 1.0
    DA_INS_LOSS_WEIGHT: 1.0
    DA_CST_LOSS_WEIGHT: 0.1
    LW_DA_INS: 0.98
  UPDATE_FACTOR:
    ONLINE: 0.2
    OFFLINE: 0.6
EVAL_PERIOD: 5
TARGET_REID_START: 0
EPS_P: 0.95
HM_THRESH: 0.3
